[project]
name = "clue-example-plugin"
version = "0.0.1"
description = "An example plugin for use with clue."
authors = [{ name = "Matthew Rafuse", email = "Matthew.Rafuse@cyber.gc.ca" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = ["clue-api (>=1.0.1.49,<2.0.0.0)"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
